POST http://localhost:8000/get_form/ HTTP/1.1
# Content-Type: application/x-www-form-urlencoded
Content-Type: application/json

{
    "lead_email": "username@domain.com",
    "phone_number": "+77 222 890 12 34 56"
}


